---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
```{r, echo = FALSE, message =FALSE}

library(tropo)
 library(ncdf4)
library(rgdal)
#broken here needs tropo.path
```

# tropo

Tools to tile rasters. 

## Example

We have a topography file installed. 

```{r,eval=FALSE}
library(tropo)
topofile <- tropo:::.etopo2()

print(topofile)
```
```{r,eval=TRUE,echo=FALSE}

topofile <- tropo:::.etopo2()

print(gsub(paste0(getOption("tropo.path"), "/"), "", topofile))
```

Create a tiling scheme. 
```{r}
r <- raster(topofile)
ts <- tiles(raster(topofile), blockX = 1024, blockY = 1024)
```

Compare it to the input: 

```{r}
r
ts$tileraster
```

Generate actual tiles with it. 

```{r,eval=FALSE}
 for (i in seq(ncell(ts$tileraster))) {
   tile <- crop(r, ts$poly[i, ], snap = "out")
   save(tile, file = sprintf("output/tile_%03i.rdata", i))
 }
```

Select a tile. 

```{r}
library(maptools)
data(wrld_simpl)
plot(wrld_simpl)
plot(ts$poly, add = TRUE)
text(ts$poly, lab = ts$poly$tile)
#dput(ts$poly$tile[click(ts$poly, n = 1)])
## 54L
```

Plot that tile. 

```{r}
load(sprintf("output/tile_%03i.rdata", 54))
plot(tile)
plot(wrld_simpl, add = TRUE)
```
